#MAIN CONFIG
account_id:
  dev: 863843292085
  prod: 810041203434

aws_profile:
  dev: vcoredev
  prod: vcoreprod

region:
  dev: us-west-2
  prod: us-west-2

environment:
  dev: dev
  prod: prod

vpc_id:
  dev: vpc-0ea142e05b5bd34e9
  prod: vpc-010e3f19a542cdd2d

continuous_integration:
  dev: $true
  prod: $true