#MAIN CONFIG
account_id:
  dev: 863843292085
  prod: 810041203434

aws_profile:
  dev: vcoredev
  prod: vcoreprod

region:
  dev: us-east-1
  prod: us-east-2

environment:
  dev: dev
  prod: prod

vpc_id:
  dev: vpc-2fb16a44
  prod: vpc-f1699d97

continuous_integration:
  dev: $true
  prod: $null